name = "HybridVariationalInference"
uuid = "a108c475-a4e2-4021-9a84-cfa7df242f64"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[weakdeps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
Combinatorics = "1.0.2"
ComponentArrays = "0.15.19"
Flux = "v0.15.2"
Lux = "1.4.2"
Random = "1.10.0"
SimpleChains = "0.4"
julia = "1.10"

[extensions]
HybridVariationalInferenceSimpleChainsExt = "SimpleChains"
HybridVariationalInferenceFluxExt = "Flux"
HybridVariationalInferenceLuxExt = "Lux"

[workspace]
projects = ["test", "docs"]