name = "HybridVariationalInference"
uuid = "a108c475-a4e2-4021-9a84-cfa7df242f64"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[deps]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"

[extensions]
HybridVariationalInferenceFluxExt = "Flux"
HybridVariationalInferenceLuxExt = "Lux"
HybridVariationalInferenceSimpleChainsExt = "SimpleChains"

[compat]
BlockDiagonals = "0.1.42"
CUDA = "5.5.2"
ChainRulesCore = "1.25"
Combinatorics = "1.0.2"
ComponentArrays = "0.15.19"
Flux = "v0.15.2"
GPUArraysCore = "0.1, 0.2"
LinearAlgebra = "1.10.0"
Lux = "1.4.2"
Random = "1.10.0"
SimpleChains = "0.4"
StatsBase = "0.34.4"
StatsFuns = "1.3.2"
TransformVariables = "0.8.10"
Zygote = "0.6.73, 0.7"
julia = "1.10"

[workspace]
projects = ["test", "docs"]
